{
  "modified": "2025-07-31T19:14:39Z",
  "published": "2025-07-31T19:14:39Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-5107",
    "SNYK-PYTHON-COLORIZATOR-10305007"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "colorizator"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLORIZATOR-10305007"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/colorizator/MAL-2025-5107.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "6dcbc6dba1ed18b825424f864f1a63261e4ad62a7be96f0f32c2f6312ad8fa03",
        "import_time": "2025-08-01T10:41:35.193405009Z",
        "id": "RLUA-2025-03571",
        "modified_time": "2025-07-31T19:14:39Z"
      }
    ]
  }
}
