{
  "modified": "2025-09-26T09:13:42Z",
  "published": "2025-09-26T09:13:42Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-2929",
    "SNYK-PYTHON-ACLOUDCLIENT-12201342"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "acloud-client"
      }
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://x.com/ReversingLabs/status/1900198602242204003"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/acloud-client/MAL-2025-2929.json"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ACLOUDCLIENT-12201342"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "a468d481d3efdbe0a84f9814bf6d236de3b81b2130c29d5ff2529d6bdb99136d",
        "import_time": "2025-09-26T11:06:09.882703014Z",
        "id": "RLUA-2025-04742",
        "modified_time": "2025-09-26T09:13:42Z"
      }
    ]
  }
}
