{
  "modified": "2025-07-31T19:14:36Z",
  "published": "2025-07-31T19:14:36Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2025-5102",
    "SNYK-PYTHON-COLORAIZ-10305008"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "coloraiz"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLORAIZ-10305008"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/coloraiz/MAL-2025-5102.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "1a7ffe6fe6d8fd9746f01735fc68e8d4a9d8bd7ab89a54c16b6a7e1bebcf8b5e",
        "import_time": "2025-08-01T10:41:34.878864893Z",
        "id": "RLUA-2025-03566",
        "modified_time": "2025-07-31T19:14:36Z"
      }
    ]
  }
}
